WDI Prospects Browser/config/routes.rb
WdiProspectsBrowser::Application.routes.draw do

  resources :wdi_refined_prospects


  resources :change_histories


  resources :users
  resources :wdi_prospects
  resources :sessions
  resources :password_resets

  get "log_in" => "sessions#new", :as => "log_in"
  
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"

  get "search" => "wdi_prospects#search", :as => "search"
  #Search WDI Refined Propspects
  get "search_refined_prospects" => "wdi_refined_prospects#searchRefinedProspects", :as => "search_refined_prospects"

  #Import records to Prospects table
  get "uploadfile" => "wdi_prospects#uploadfile", :as => "uploadfile"
  post "import" => "wdi_prospects#import", :as => "import"
  
  #Import records to Refined-Prospects table
  #get "upload_refined_file" => "wdi_refined_prospects#uploadRefinedFile", :as => "upload_refined_file"
  post "import_to_refined" => "wdi_refined_prospects#importToRefined", :as => "import_to_refined"
  
  # Del Prospects
  post "delProspects" => "wdi_prospects#delProspects", :as => "delProspects"
  # Del Refined Prospects
  post "del_refined_prospects" => "wdi_refined_prospects#delRefinedProspects", :as => "del_refined_prospects"
  

  get "home/index"
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#new'
  
end

WDI Prospects Browser/app/models/wdi_refined_prospect.rb
class WdiRefinedProspect < ActiveRecord::Base
  attr_accessible :address, :city, :e_i_n, :email, :first_name, :has_donation_button, :income_amount, :last_name, :name, :state, :title, :website

  validates :e_i_n, :presence => true
  validates_uniqueness_of :e_i_n
  #def self.search(params = {})
  def self.search(srchName, srchEin, srchAddr, srchCity, srchState, srchIncAmnt, srchFirstName, srchLastName,
        srchEmail, srchTitle, srchHasDonBut, srchWebsite, recLimit)
    if srchName || srchEin || srchAddr || srchCity || srchState || srchIncAmnt || srchFirstName  || srchLastName || srchEmail || srchTitle || srchHasDonBut || srchWebsite
      
      query = String.new

      if srchName!=""
        query = "name LIKE ? AND "
      else
        query ="(name LIKE ? or name IS NULL) AND "
      end
      
      if srchEin!=""
        query = query + "e_i_n LIKE ? AND "
      else
        query = query + "(e_i_n LIKE ? or e_i_n IS NULL) AND "
      end
      
      if srchAddr!=""
        query = query + "address LIKE ? AND "
      else
        query = query + "(address LIKE ? or address IS NULL) AND "
      end
      
      if srchCity!=""
        query = query + "city LIKE ? AND "
      else
        query = query + "(city LIKE ? or city IS NULL) AND "
      end
      
      if srchState!=""
        query = query + "state LIKE ? AND "
      else
        query = query + "(state LIKE ? or state IS NULL) AND "
      end

      if srchIncAmnt!=""
        if (srchIncAmnt.include? ">") || (srchIncAmnt.include? "<")
          query = query + "income_amount #{srchIncAmnt} AND "
        end
      else
        query = query + "(income_amount LIKE '%%' or income_amount IS NULL) AND "
      end
      
      if srchFirstName!=""
        query = query + "first_name LIKE ? AND "
      else
        query = query + "(first_name LIKE ? or first_name IS NULL) AND "
      end
      
      if srchLastName!=""
        query = query + "last_name LIKE ? AND "
      else
        query = query + "(last_name LIKE ? or last_name IS NULL) AND "
      end
      
      if srchEmail!=""
        query = query + "email LIKE ? AND "
      else
        query = query + "(email LIKE ? or email IS NULL) AND "
      end
      
      if srchTitle!=""
        query = query + "title LIKE ? AND "
      else
        query = query + "(title LIKE ? or title IS NULL) AND "
      end
      
      if srchHasDonBut!=""
        query = query + "has_donation_button LIKE ? AND "
      else
        query = query + "(has_donation_button LIKE ? or has_donation_button IS NULL) AND "
      end
      
      if srchWebsite!=""
        query = query + "website LIKE ?"
      else
        query = query + "(website LIKE ? or website IS NULL)"
      end
      
      if recLimit!=""
        find(:all, :conditions => [query,
            "%#{srchName}%", "%#{srchEin}%", "%#{srchAddr}%", "%#{srchCity}%", "%#{srchState}%", "%#{srchFirstName}%", 
                "%#{srchLastName}%", "%#{srchEmail}%", "%#{srchTitle}%", "%#{srchHasDonBut}%", "%#{srchWebsite}%"], :limit => Integer(recLimit))
      else
        find(:all, :conditions => [query,
                        "%#{srchName}%", "%#{srchEin}%", "%#{srchAddr}%", "%#{srchCity}%", "%#{srchState}%", "%#{srchFirstName}%", 
                            "%#{srchLastName}%", "%#{srchEmail}%", "%#{srchTitle}%", "%#{srchHasDonBut}%", "%#{srchWebsite}%"])
      end
        
             
    end
  end



end

WDI Prospects Browser/app/controllers/wdi_refined_prospects_controller.rb
class WdiRefinedProspectsController < ApplicationController

  # GET /wdi_refined_prospects/1
  # GET /wdi_refined_prospects/1.json
  def show
@wdi_refined_prospect = WdiRefinedProspect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wdi_refined_prospect }
    end
  end

  # GET /wdi_refined_prospects/new
  # GET /wdi_refined_prospects/new.json
  def new
    sessUser = session[:user_id]
    if sessUser      
      @wdi_refined_prospect = WdiRefinedProspect.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @wdi_refined_prospect }
      end
    else
      redirect_to '/log_in'
    end
  end

  # GET /wdi_refined_prospects/1/edit
  def edit
    @wdi_refined_prospect = WdiRefinedProspect.find(params[:id])
  end

  # POST /wdi_refined_prospects
  # POST /wdi_refined_prospects.json
  def create
    @wdi_refined_prospect = WdiRefinedProspect.new(params[:wdi_refined_prospect])
    chngStr = "<b>Created Refined prospect with EIN: "+params[:wdi_refined_prospect][:e_i_n]+"</b>"
    respond_to do |format|
      if @wdi_refined_prospect.save
        @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chngStr)
        @change_history.save
        format.html { redirect_to @wdi_refined_prospect, notice: 'Prospect was successfully created.' }
        format.json { render json: @wdi_refined_prospect, status: :created, location: @wdi_refined_prospect }
      else
        format.html { render action: "new" }
        format.json { render json: @wdi_refined_prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wdi_refined_prospects/1
  # PUT /wdi_refined_prospects/1.json
  def update
    @wdi_refined_prospect = WdiRefinedProspect.find(params[:id])
    
    chngStr = "<b><u>Edited EIN: "+ String(@wdi_refined_prospect.e_i_n)
    chngStr = chngStr +" with below changes:</u></b>"
    if @wdi_refined_prospect.e_i_n != params[:wdi_refined_prospect][:e_i_n]
      chngStr = "<br/>E I N: " + params[:wdi_refined_prospect][:e_i_n]
    end
    if @wdi_refined_prospect.name != params[:wdi_refined_prospect][:name]
      chngStr = chngStr +"<br/>"+"Name: "+params[:wdi_refined_prospect][:name]
    end
    if @wdi_refined_prospect.address != params[:wdi_refined_prospect][:address]
      chngStr = chngStr +"<br/>"+"Address: "+params[:wdi_refined_prospect][:address]
    end
    if @wdi_refined_prospect.city != params[:wdi_refined_prospect][:city]
      chngStr = chngStr +"<br/>"+"City: "+params[:wdi_refined_prospect][:city]
    end
    if @wdi_refined_prospect.state != params[:wdi_refined_prospect][:state]
      chngStr = chngStr +"<br/>"+"State: "+params[:wdi_refined_prospect][:state]
    end
    
    params[:wdi_refined_prospect][:income_amount] != "" ? incAmnt = params[:wdi_refined_prospect][:income_amount] : incAmnt = ""
    if String(@wdi_refined_prospect.income_amount) != incAmnt
      chngStr = chngStr +"<br/>"+"Income Amount: "+incAmnt
    end
    if @wdi_refined_prospect.first_name != params[:wdi_refined_prospect][:first_name]
      chngStr = chngStr +"<br/>"+"First Name: "+params[:wdi_refined_prospect][:first_name]
    end
    if @wdi_refined_prospect.last_name != params[:wdi_refined_prospect][:last_name]
      chngStr = chngStr +"<br/>"+"Last Name: "+params[:wdi_refined_prospect][:last_name]
    end
    if @wdi_refined_prospect.email != params[:wdi_refined_prospect][:email]
      chngStr = chngStr +"<br/>"+"Email: "+params[:wdi_refined_prospect][:email]
    end
    if @wdi_refined_prospect.title != params[:wdi_refined_prospect][:title]
      chngStr = chngStr +"<br/>"+"Title: "+params[:wdi_refined_prospect][:title]
    end
    if @wdi_refined_prospect.has_donation_button != params[:wdi_refined_prospect][:has_donation_button]
      chngStr = chngStr +"<br/>"+"Donation Button: "+params[:wdi_refined_prospect][:has_donation_button]
    end
    if @wdi_refined_prospect.website != params[:wdi_refined_prospect][:website]
      chngStr = chngStr +"<br/>"+"Website: "+params[:wdi_refined_prospect][:website]
    end
    
    respond_to do |format|
      if @wdi_refined_prospect.update_attributes(params[:wdi_refined_prospect])
        @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chngStr)
        @change_history.save
        format.html { redirect_to @wdi_refined_prospect, notice: 'Wdi prospect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wdi_refined_prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wdi_refined_prospects/1
  # DELETE /wdi_refined_prospects/1.json
  def destroy
    @wdi_refined_prospect = WdiRefinedProspect.find(params[:id])

    chng = "<b>Deleted Refined Prospect with EIN: "+String(@wdi_refined_prospect.e_i_n)+"</b>"
    @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chng)
    @change_history.save
      
    @wdi_refined_prospect.destroy

    respond_to do |format|
      format.html { redirect_to "/search_refined_prospects" }
    end
  end
  
  # Search functionality
  def searchRefinedProspects
    sessUser = session[:user_id]
    if sessUser        
      @wdi_refined_prospects = WdiRefinedProspect.search(params[:srchName], params[:srchEin], params[:srchAddr], 
              params[:srchCity], params[:srchState], params[:srchIncAmnt], params[:srchFirstName], params[:srchLastName],params[:srchEmail],
                  params[:srchTitle], params[:srchHasDonBut], params[:srchWebsite], params[:recLimit])      
      respond_to do |format|
        format.html
        format.json { render json: @wdi_refined_prospects }
      end
    else
      redirect_to '/log_in'
    end
  end
  
  # uploadfile
  def uploadfile
    sessUser = session[:user_id]
    if sessUser 
      render :file => 'wdi_prospects/uploadfile.html.erb'
    else
      redirect_to '/log_in'
    end
  end
  
  # Action class to Import records from CSV into wdi_refined_prospects
  def importToRefined
    srcFile = params[:file]
    n=0
    CSV.foreach(srcFile.path, :headers => true) do |row|
      bool = String
      String(row[10]) == "true" ? bool = "1" : bool = "0"
      WdiRefinedProspect.create({
      :e_i_n => row[0],
      :name => row[1],    
      :address => row[2],
      :city => row[3],
      :state => row[4],
      :income_amount => replChar(row[5]),
      :first_name => row[6],
      :last_name => row[7],
      :email => row[8],
      :title => row[9],
      :has_donation_button => bool,
      :website => row[11]
      })
      n=n+1
    end
    respond_to do |format|
      format.html { 
        flash[:notice] = "#{n} Records imported successfully"
        render :file => "wdi_prospects/uploadfile.html.erb" 
      }
    end
    #render :file => 'wdi_prospects/uploadfile.html.erb', :notice => "Records updated"
  end
  
  #Util function used in import action to remove unwanted characters
  def replChar(amount)
    if amount.strip.length!=0
      amount=amount.strip
      amount.gsub!('$','')
      amount.gsub!(',','')
    end
  return amount
  end
  
  # Action class to delete multiple prospects
  def delRefinedProspects
#    session[:return_to] = request.fullpath
    params[:delProspectIds].split("$").each do |id|
      @wdi_refined_prospect = WdiRefinedProspect.find(id)
      
      chng = "<b>Deleted Prospect with EIN: "+String(@wdi_refined_prospect.e_i_n)+"</b>"
      @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chng)
      @change_history.save
      
      @wdi_refined_prospect.destroy
    end
    #redirect_to(session[:return_to] || "/search")
#    session[:return_to] = nil
    respond_to do |format|
      format.html { render action: "searchRefinedProspects" }
    end
  rescue => e
    return e.message
  end

end

WDI Prospects Browser/app/helpers/wdi_refined_prospects_helper.rb
module WdiRefinedProspectsHelper
end

WDI Prospects Browser/app/views/wdi_refined_prospects/edit.html.erb
<div class="center-div">
	<h1>Edit Prospect</h1>
	<%= render 'form' %>
</div>

WDI Prospects Browser/app/views/wdi_refined_prospects/index.html.erb
<h1>Listing wdi_refined_prospects</h1>

<table>
  <tr>
    <th>E i n</th>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Income amount</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Title</th>
    <th>Has donation button</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wdi_refined_prospects.each do |wdi_refined_prospect| %>
  <tr>
    <td><%= wdi_refined_prospect.e_i_n %></td>
    <td><%= wdi_refined_prospect.name %></td>
    <td><%= wdi_refined_prospect.address %></td>
    <td><%= wdi_refined_prospect.city %></td>
    <td><%= wdi_refined_prospect.state %></td>
    <td><%= wdi_refined_prospect.income_amount %></td>
    <td><%= wdi_refined_prospect.first_name %></td>
    <td><%= wdi_refined_prospect.last_name %></td>
    <td><%= wdi_refined_prospect.email %></td>
    <td><%= wdi_refined_prospect.title %></td>
    <td><%= wdi_refined_prospect.has_donation_button %></td>
    <td><%= wdi_refined_prospect.website %></td>
    <td><%= link_to 'Show', wdi_refined_prospect %></td>
    <td><%= link_to 'Edit', edit_wdi_refined_prospect_path(wdi_refined_prospect) %></td>
    <td><%= link_to 'Destroy', wdi_refined_prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wdi refined prospect', new_wdi_refined_prospect_path %>

WDI Prospects Browser/app/views/wdi_refined_prospects/new.html.erb
<div class="center-div">
	<h1>New Refined Prospect</h1>
	<%= render 'form' %>
</div>

WDI Prospects Browser/app/views/wdi_refined_prospects/searchRefinedProspects.html.erb
<script>
	var curUrl ="";
	$(document).ready(function() 
    { 
        $("#prospResTab").tablesorter(); 
        $("#prospResTab").tablesorter({ headers: { 0: { sorter: false} } }); 
    	curUrl = $(location).attr('href');
    }); 
    
	function exportToXl() {
		var excelHtml = "<table><tr><th>E.I.N</th><th>Name</th><th>Address</th><th>City</th>"
					+"<th>State</th><th>Income Amount</th><th>First Name</th><th>Last Name</th>"
				+"<th>Email</th><th>Title</th><th>Has Donation Button</th><th>Website</th></tr>";
		
		$(".prosp-res-tab tr:has(input:checked)").each(function(){
			excelHtml = excelHtml + "<tr>";
			var count =1;
			$(this).find("td:not(#xlExcld)").each(function(){
				if(count==2 || count==3 || count==4 || count==10)
				{
					excelHtml = excelHtml + "<td>=PROPER(\"" + $(this).html() + "\")</td>";
				}
				else
				{
					excelHtml = excelHtml + "<td>" + $(this).html() + "</td>";
				}
				count=count+1;
			});			
			excelHtml = excelHtml + "</tr>";
			
		});			
		
		excelHtml = excelHtml + "</table>";
		
	    window.open('data:application/vnd.ms-excel,' + encodeURIComponent(excelHtml + "</table>"));
	}
	var isChecked = 0;
	function chkUnchkAll() {
		if ($(".mstrDelChkBox").is(":checked")) {
			$('.delChkBox').attr('checked', 'checked');
		} else {
			$('.delChkBox').removeAttr('checked');
		}
	}

	function delProspects() {
		var delProspectIds = "";
		var chkBoxes = $("input:checked");
		i = chkBoxes.length;
		if (i == 0) {
			alert("Please select a Prospect to delete");
		} 
		else
		{
			while (i--) {
				delProspectIds = delProspectIds + chkBoxes[i].id + "$";
			}
			var cnfrm = confirm("Are you sure you want to delete "+chkBoxes.length+" prospects?");
			if (cnfrm)
			{
				$.ajax({
					type : 'POST',
					beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')) },
					url : '/del_refined_prospects',
					data : {
						'delProspectIds' : delProspectIds,
					},
					success : function() {
						alert(chkBoxes.length + " Prospects deleted successfully!");
						window.location.href = curUrl;
					}
				});				
			}
		}
	}

</script>
<div align="center" style="padding:5px;height:520px; width:1200px;" >
	<%= form_tag search_refined_prospects_path, :method => 'get' do %>
	<table class="prosp-master-tab" style="border:none;">
		<tr>
			<td style="padding:0px;">
			<table class="srch-fields-tab">
				<tr>
					<td><%= label :name, "Name: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchName, params[:srchName] %></td>
				</tr>
				<tr>
					<td><%= label :e_i_n, "E I N: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchEin, params[:srchEin] %></td>
				</tr>
				<tr>
					<td><%= label :address, "Address: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchAddr, params[:srchAddr] %></td>
				</tr>
				<tr>
					<td><%= label :city, "City: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchCity, params[:srchCity] %></td>
				</tr>
				<tr>
					<td><%= label :state, "State: " %></td>
				</tr>
				<tr>
					<td>
					<select id="srchState" name="srchState" >
						<option selected="selected" value=""></option>
						<option value="AL">AL</option>
						<option value="AK">AK</option>
						<option value="AZ">AZ</option>
						<option value="AR">AR</option>
						<option value="CA">CA</option>
						<option value="CO">CO</option>
						<option value="CT">CT</option>
						<option value="DE">DE</option>
						<option value="DC">DC</option>
						<option value="FL">FL</option>
						<option value="GA">GA</option>
						<option value="HI">HI</option>
						<option value="ID">ID</option>
						<option value="IL">IL</option>
						<option value="IN">IN</option>
						<option value="IA">IA</option>
						<option value="KS">KS</option>
						<option value="KY">KY</option>
						<option value="LA">LA</option>
						<option value="ME">ME</option>
						<option value="MD">MD</option>
						<option value="MA">MA</option>
						<option value="MI">MI</option>
						<option value="MN">MN</option>
						<option value="MS">MS</option>
						<option value="MO">MO</option>
						<option value="MT">MT</option>
						<option value="NE">NE</option>
						<option value="NV">NV</option>
						<option value="NH">NH</option>
						<option value="NJ">NJ</option>
						<option value="NM">NM</option>
						<option value="NY">NY</option>
						<option value="NC">NC</option>
						<option value="ND">ND</option>
						<option value="OH">OH</option>
						<option value="OK">OK</option>
						<option value="OR">OR</option>
						<option value="PA">PA</option>
						<option value="RI">RI</option>
						<option value="SC">SC</option>
						<option value="SD">SD</option>
						<option value="TN">TN</option>
						<option value="TX">TX</option>
						<option value="UT">UT</option>
						<option value="VT">VT</option>
						<option value="VA">VA</option>
						<option value="WA">WA</option>
						<option value="WV">WV</option>
						<option value="WI">WI</option>
						<option value="WY">WY</option>
					</select></td>
				</tr>
				<tr>
					<td><%= label :income_amount, "Income Amount: " %><i style="font-size: 10px;">(e.g., >100)</i></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchIncAmnt, params[:srchIncAmnt] %></td>
				</tr>
				<tr>
					<td><%= label :first_name, "First Name: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchFirstName, params[:srchFirstName] %></td>
				</tr>
				<tr>
					<td><%= label :last_name, "Last Name: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchLastName, params[:srchLastName] %></td>
				</tr>
				<tr>
					<td><%= label :email, "Email: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchEmail, params[:srchEmail] %></td>
				</tr>
				<tr>
					<td><%= label :title, "Title: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchTitle, params[:srchTitle] %></td>
				</tr>
				<tr>
					<td><%= label :has_donation_button, "Has Donation Button: " %></td>
				</tr>
				<tr>
					<td>
						<select id="srchHasDonBut" name="srchHasDonBut" >
							<option selected="selected" value=""></option>
							<option value="1">True</option>
							<option value="0">False</option>
						</select>
					</td>
				</tr>
				<tr>
					<td><%= label :website, "Website: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchWebsite, params[:srchWebsite] %></td>
				</tr>
				<tr>
					<td><%= label :limit_records, "Limit No. of Records to: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :recLimit, params[:recLimit] %></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;<%= submit_tag "Search", :name => nil %></td>
				</tr>
			</table></td>
			<td style="padding-top:0px;">
			<table style="border:none;">
				<tr>
					<td>
					<div class="scrollContent_2">
						<table id="prospResTab" class="prosp-res-tab">
							<thead>
							<tr class="prosp-res-hdr">
								<th id="xlExcld">
								<input class="mstrDelChkBox" type="checkbox" onclick="chkUnchkAll();" >
								</th>
								<th>E.I.N</th>
								<th>Name</th>
								<th>Address</th>
								<th>City</th>
								<th>State</th>
								<th>Income amount</th>
								<th>First Name</th>
								<th>Last Name</th>
								<th>Email</th>
								<th>Title</th>
								<th>Donation Button</th>
								<th>Website</th>
								<th id="xlExcld">-</th>
								<th id="xlExcld">-</th>
							</tr>
							</thead>
							<tbody>
							<% if @wdi_refined_prospects %>
							<% @wdi_refined_prospects.each do |wdi_refined_prospect| %>
							<tr>
								<td id="xlExcld">
								<input class="delChkBox" type="checkbox" id="<%= wdi_refined_prospect.id %>" >
								</td>
								<td><%= wdi_refined_prospect.e_i_n %></td>
								<td><%= wdi_refined_prospect.name %></td>
								<td><%= wdi_refined_prospect.address %></td>
								<td><%= wdi_refined_prospect.city %></td>
								<td><%= wdi_refined_prospect.state %></td>
								<td>$<%= number_with_delimiter(wdi_refined_prospect.income_amount, :delimiter => ',') %></td>
								<td><%= wdi_refined_prospect.first_name %></td>
								<td><%= wdi_refined_prospect.last_name %></td>
								<td><%= wdi_refined_prospect.email %></td>
								<td><%= wdi_refined_prospect.title %></td>
								<td><%= wdi_refined_prospect.has_donation_button %></td>
								<td><%= wdi_refined_prospect.website %></td>
								<td id="xlExcld"><%= link_to 'Edit', edit_wdi_refined_prospect_path(wdi_refined_prospect) %></td>
								<td id="xlExcld"><%= link_to 'Destroy', wdi_refined_prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							</tr>
							<% end %>
							<% end %>
							</tbody>
						</table>
					</div></td>
				</tr>
				<tr>
					<td style="border: 1px solid #7EBD64;border-left:none;">&nbsp;&nbsp;<%= button_to_function "Delete", 'delProspects();', :id => "delBtn" %>
						&nbsp;&nbsp;<input style="width:120px;" type="button" onclick="exportToXl();" value="Export to Excel">
					</td>
				</tr>

			</table></td>
		</tr>
	</table>
	<% end %>
</div>
	

WDI Prospects Browser/app/views/wdi_refined_prospects/show.html.erb
<div class="center-div">
<p id="notice"><%= notice %></p>

<p>
  <b>E i n:</b>
  <%= @wdi_refined_prospect.e_i_n %>
</p>

<p>
  <b>Name:</b>
  <%= @wdi_refined_prospect.name %>
</p>

<p>
  <b>Address:</b>
  <%= @wdi_refined_prospect.address %>
</p>

<p>
  <b>City:</b>
  <%= @wdi_refined_prospect.city %>
</p>

<p>
  <b>State:</b>
  <%= @wdi_refined_prospect.state %>
</p>

<p>
  <b>Income amount:</b>
  <%= @wdi_refined_prospect.income_amount %>
</p>

<p>
  <b>First name:</b>
  <%= @wdi_refined_prospect.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @wdi_refined_prospect.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @wdi_refined_prospect.email %>
</p>

<p>
  <b>Title:</b>
  <%= @wdi_refined_prospect.title %>
</p>

<p>
  <b>Has donation button:</b>
  <%= @wdi_refined_prospect.has_donation_button %>
</p>

<p>
  <b>Website:</b>
  <%= @wdi_refined_prospect.website %>
</p>


<%= link_to 'Edit', edit_wdi_refined_prospect_path(@wdi_refined_prospect) %> |
</div>