WDI Prospects Browser/config/routes.rb
WdiProspectsBrowser::Application.routes.draw do

  resources :wdi_refined_prospects


  resources :change_histories


  resources :users
  resources :wdi_prospects
  resources :sessions
  resources :password_resets

  get "log_in" => "sessions#new", :as => "log_in"
  
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"

  get "search" => "wdi_prospects#search", :as => "search"
  #Search WDI Refined Propspects
  get "search_refined_prospects" => "wdi_refined_prospects#searchRefinedProspects", :as => "search_refined_prospects"

  #Import records to Prospects table
  get "uploadfile" => "wdi_prospects#uploadfile", :as => "uploadfile"
  post "import" => "wdi_prospects#import", :as => "import"
  
  #Import records to Refined-Prospects table
  #get "upload_refined_file" => "wdi_refined_prospects#uploadRefinedFile", :as => "upload_refined_file"
  post "import_to_refined" => "wdi_refined_prospects#importToRefined", :as => "import_to_refined"
  
  # Del Prospects
  post "delProspects" => "wdi_prospects#delProspects", :as => "delProspects"
  # Del Refined Prospects
  post "del_refined_prospects" => "wdi_refined_prospects#delRefinedProspects", :as => "del_refined_prospects"
  

  get "home/index"
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#new'
  
end

WDI Prospects Browser/app/models/wdi_prospect.rb
class WdiProspect < ActiveRecord::Base
  attr_accessible :address, :asset_amount, :city, :e_i_n, :form_990_revenue_amount, :in_care_of_name, :income_amount, :name, :state, :zip_code

  validates :e_i_n, :presence => true
  validates_uniqueness_of :e_i_n
  #def self.search(params = {})
  def self.search(srchName, srchEin, srchInCareOfName, srchAddr, srchCity, srchState, srchZipCode, srchAstAmnt, srchIncAmnt, srchFrm990RvnAmnt, recLimit)
    if srchName || srchEin || srchInCareOfName || srchAddr || srchCity || srchState || srchZipCode || srchAstAmnt || srchIncAmnt || srchFrm990RvnAmnt
      
      query = String.new

      if srchName!=""
        query = "name LIKE ? AND "
      else
        query ="(name LIKE ? or name IS NULL) AND "
      end
      
      if srchEin!=""
        query = query + "e_i_n LIKE ? AND "
      else
        query = query + "(e_i_n LIKE ? or e_i_n IS NULL) AND "
      end
      
      if srchInCareOfName!=""
        query = query + "in_care_of_name LIKE ? AND "
      else
        query = query + "(in_care_of_name LIKE ? or in_care_of_name IS NULL) AND "
      end
      
      if srchAddr!=""
        query = query + "address LIKE ? AND "
      else
        query = query + "(address LIKE ? or address IS NULL) AND "
      end
      
      if srchCity!=""
        query = query + "city LIKE ? AND "
      else
        query = query + "(city LIKE ? or city IS NULL) AND "
      end
      
      if srchState!=""
        query = query + "state LIKE ? AND "
      else
        query = query + "(state LIKE ? or state IS NULL) AND "
      end
      
      if srchZipCode!=""
        query = query + "zip_code LIKE ? AND "
      else
        query = query + "(zip_code LIKE ? or zip_code IS NULL) AND "
      end
            
      #Check if amount related fields have > or < signs in them
      #If so use them in the query as it is
      if srchAstAmnt!=""
        if (srchAstAmnt.include? ">") || (srchAstAmnt.include? "<")
          query = query + "asset_amount #{srchAstAmnt} AND "
        end
      else
        query = query + "(asset_amount LIKE '%%' or asset_amount IS NULL) AND "
      end

      if srchIncAmnt!=""
        if (srchIncAmnt.include? ">") || (srchIncAmnt.include? "<")
          query = query + "income_amount #{srchIncAmnt} AND "
        end
      else
        query = query + "(income_amount LIKE '%%' or income_amount IS NULL) AND "
      end

      if srchFrm990RvnAmnt!=""
        if (srchFrm990RvnAmnt.include? ">") || (srchFrm990RvnAmnt.include? "<")
          query = query + "form_990_revenue_amount #{srchFrm990RvnAmnt}"
        end
      else
        query = query + "(form_990_revenue_amount LIKE '%%' or form_990_revenue_amount IS NULL)"
      end
      
      if recLimit!=""
        find(:all, :conditions => [query,
            "%#{srchName}%", "%#{srchEin}%", "%#{srchInCareOfName}%", "%#{srchAddr}%", "%#{srchCity}%", 
              "%#{srchState}%", "%#{srchZipCode}%"], :limit => Integer(recLimit))
      else
        find(:all, :conditions => [query,
            "%#{srchName}%", "%#{srchEin}%", "%#{srchInCareOfName}%", "%#{srchAddr}%", "%#{srchCity}%", 
              "%#{srchState}%", "%#{srchZipCode}%"])
      end
        
             
    end
  end

end

WDI Prospects Browser/app/controllers/wdi_prospects_controller.rb
require 'csv'

class WdiProspectsController < ApplicationController

  # GET /wdi_prospects/1
  # GET /wdi_prospects/1.json
  def show
    @wdi_prospect = WdiProspect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wdi_prospect }
    end
  end

  # GET /wdi_prospects/new
  # GET /wdi_prospects/new.json
  def new
    sessUser = session[:user_id]
    if sessUser      
      @wdi_prospect = WdiProspect.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @wdi_prospect }
      end
    else
      redirect_to '/log_in'
    end
  end

  # GET /wdi_prospects/1/edit
  def edit
    @wdi_prospect = WdiProspect.find(params[:id])
  end

  # POST /wdi_prospects
  # POST /wdi_prospects.json
  def create
    @wdi_prospect = WdiProspect.new(params[:wdi_prospect])
    chngStr = "<b>Created a prospect with EIN: "+params[:wdi_prospect][:e_i_n]+"</b>"
    respond_to do |format|
      if @wdi_prospect.save
        @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chngStr)
        @change_history.save
        format.html { redirect_to @wdi_prospect, notice: 'Wdi prospect was successfully created.' }
        format.json { render json: @wdi_prospect, status: :created, location: @wdi_prospect }
      else
        format.html { render action: "new" }
        format.json { render json: @wdi_prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wdi_prospects/1
  # PUT /wdi_prospects/1.json
  def update
    @wdi_prospect = WdiProspect.find(params[:id])
    
    #Create entry to change history table
    #Find out the fields that are changed
    #<b> are added to make them appear bold in the view
    chngStr = "<b><u>Edited EIN: "+ @wdi_prospect.e_i_n
    chngStr = chngStr +" with below changes:</u></b>"
    if @wdi_prospect.e_i_n != params[:wdi_prospect][:e_i_n]
      chngStr = "<br/>E I N: " + params[:wdi_prospect][:e_i_n]
    end
    if @wdi_prospect.name != params[:wdi_prospect][:name]
      chngStr = chngStr +"<br/>"+"Name: "+params[:wdi_prospect][:name]
    end
    if @wdi_prospect.in_care_of_name != params[:wdi_prospect][:in_care_of_name]
      chngStr = chngStr +"<br/>"+"In Care Of Name: "+params[:wdi_prospect][:in_care_of_name]
    end
    if @wdi_prospect.address != params[:wdi_prospect][:address]
      chngStr = chngStr +"<br/>"+"Address: "+params[:wdi_prospect][:address]
    end
    if @wdi_prospect.city != params[:wdi_prospect][:city]
      chngStr = chngStr +"<br/>"+"City: "+params[:wdi_prospect][:city]
    end
    if @wdi_prospect.state != params[:wdi_prospect][:state]
      chngStr = chngStr +"<br/>"+"State: "+params[:wdi_prospect][:state]
    end
    if @wdi_prospect.zip_code != params[:wdi_prospect][:zip_code]
      chngStr = chngStr +"<br/>"+"Zip Code: "+params[:wdi_prospect][:zip_code]
    end

    params[:wdi_prospect][:asset_amount] != "" ? astAmnt = params[:wdi_prospect][:asset_amount] : astAmnt = ""      
    if String(@wdi_prospect.asset_amount) != astAmnt
      chngStr = chngStr +"<br/>"+"Asset Amount: "+astAmnt
    end
    
    params[:wdi_prospect][:income_amount] != "" ? incAmnt = params[:wdi_prospect][:income_amount] : incAmnt = ""
    if String(@wdi_prospect.income_amount) != incAmnt
      chngStr = chngStr +"<br/>"+"Income Amount: "+incAmnt
    end
    
    params[:wdi_prospect][:form_990_revenue_amount] != "" ? formAmnt = params[:wdi_prospect][:form_990_revenue_amount] : formAmnt = ""
    if String(@wdi_prospect.form_990_revenue_amount) != formAmnt
      chngStr = chngStr +"<br/>"+"Form 990 Revenue Amount: "+formAmnt
    end
    
    respond_to do |format|
      if @wdi_prospect.update_attributes(params[:wdi_prospect])
        @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chngStr)
        @change_history.save
        format.html { redirect_to @wdi_prospect, notice: 'Wdi prospect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wdi_prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wdi_prospects/1
  # DELETE /wdi_prospects/1.json
  def destroy
    @wdi_prospect = WdiProspect.find(params[:id])

    chng = "<b>Deleted Prospect with EIN: "+@wdi_prospect.e_i_n+"</b>"
    @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chng)
    @change_history.save
      
    @wdi_prospect.destroy

    respond_to do |format|
      format.html { redirect_to "/search" }
    end
  end
  
  # Search functionality
  def search
    sessUser = session[:user_id]
    if sessUser        
      @wdi_prospects = WdiProspect.search(params[:srchName], params[:srchEin], params[:srchInCareOfName],
                params[:srchAddr], params[:srchCity], params[:srchState], params[:srchZipCode], 
                  params[:srchAstAmnt], params[:srchIncAmnt], params[:srchFrm990RvnAmnt], params[:recLimit])      
      respond_to do |format|
        format.html
        format.json { render json: @wdi_prospects }
      end
    else
      redirect_to '/log_in'
    end
  end
  
  # uploadfile
  def uploadfile
    sessUser = session[:user_id]
    if sessUser 
      render :file => 'wdi_prospects/uploadfile.html.erb'
    else
      redirect_to '/log_in'
    end
  end
  
  # Action class to Import records from CSV into wdi_prospects
  def import
    srcFile = params[:file]
    n=0
    CSV.foreach(srcFile.path, :headers => true) do |row|
      WdiProspect.create({
      :e_i_n => row[0],
      :name => row[1],    
      :in_care_of_name => row[2],
      :address => row[3],
      :city => row[4],
      :state => row[5],
      :zip_code => row[6],
      :asset_amount => replChar(row[25]),
      :income_amount => replChar(row[26]),
      :form_990_revenue_amount => replChar(row[28])
      })
      n=n+1
    end
    respond_to do |format|
      format.html { 
        flash[:notice] = "#{n} Records imported successfully"
        render :file => "wdi_prospects/uploadfile.html.erb" 
      }
end
  end
  
  #Util function used in import action to remove unwanted characters
  def replChar(amount)
    if amount.strip.length!=0
      amount=amount.strip
      amount.gsub!('$','')
      amount.gsub!(',','')
    end
  return amount
  end
  
  # Action class to delete multiple prospects
  def delProspects
#    session[:return_to] = request.fullpath
    params[:delProspectIds].split("$").each do |id|
      @wdi_prospect = WdiProspect.find(id)
      
      chng = "<b>Deleted Prospect with EIN: "+@wdi_prospect.e_i_n+"</b>"
      @change_history = ChangeHistory.new(username: session[:user_name], email: session[:user_email], change: chng)
      @change_history.save
      
      @wdi_prospect.destroy
    end
    #redirect_to(session[:return_to] || "/search")
#    session[:return_to] = nil
    respond_to do |format|
      format.html { render action: "search" }
    end
  rescue => e
    return e.message
  end
  
end

WDI Prospects Browser/app/helpers/wdi_prospects_helper.rb
module WdiProspectsHelper
end

WDI Prospects Browser/app/views/wdi_prospects/_form.html.erb
<%= form_for(@wdi_prospect) do |f| %>
  <% if @wdi_prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wdi_prospect.errors.count, "error") %> prohibited this wdi_prospect from being saved:</h2>

      <ul>
      <% @wdi_prospect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<table class="wdi-prospect-tab">
		<tr>
			<td class="label-td"><%= f.label :e_i_n %></td>
			<td><%= f.text_field :e_i_n %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :name %></td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :in_care_of_name %></td>
			<td><%= f.text_field :in_care_of_name %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :address %></td>
			<td><%= f.text_field :address %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :city %></td>
			<td><%= f.text_field :city %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :state %></td>
			<td><%= f.text_field :state %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :zip_code %></td>
			<td><%= f.text_field :zip_code %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :asset_amount %></td>
			<td><%= f.text_field :asset_amount %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :income_amount %></td>
			<td><%= f.text_field :income_amount %></td>
		</tr>
		<tr>
			<td class="label-td"><%= f.label :form_990_revenue_amount %></td>
			<td><%= f.text_field :form_990_revenue_amount %></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><%= f.submit %></td>
		</tr>
	</table>
<% end %>

WDI Prospects Browser/app/views/wdi_prospects/edit.html.erb
<div class="center-div">
	<h1>Edit Prospect</h1>
	<%= render 'form' %>
</div>

WDI Prospects Browser/app/views/wdi_prospects/index.html.erb
<h1>Listing wdi_prospects</h1>

<table>
  <tr>
    <th>E i n</th>
    <th>Name</th>
    <th>In care of name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip code</th>
    <th>Asset amount</th>
    <th>Income amount</th>
    <th>Form 990 revenue amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wdi_prospects.each do |wdi_prospect| %>
  <tr>
    <td><%= wdi_prospect.e_i_n %></td>
    <td><%= wdi_prospect.name %></td>
    <td><%= wdi_prospect.in_care_of_name %></td>
    <td><%= wdi_prospect.address %></td>
    <td><%= wdi_prospect.city %></td>
    <td><%= wdi_prospect.state %></td>
    <td><%= wdi_prospect.zip_code %></td>
    <td><%= wdi_prospect.asset_amount %></td>
    <td><%= wdi_prospect.income_amount %></td>
    <td><%= wdi_prospect.form_990_revenue_amount %></td>
    <td><%= link_to 'Show', wdi_prospect %></td>
    <td><%= link_to 'Edit', edit_wdi_prospect_path(wdi_prospect) %></td>
    <td><%= link_to 'Destroy', wdi_prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wdi prospect', new_wdi_prospect_path %>

WDI Prospects Browser/app/views/wdi_prospects/new.html.erb
<div class="center-div">
	<h1>New Prospect</h1>
	<%= render 'form' %>
</div>

WDI Prospects Browser/app/views/wdi_prospects/search.html.erb
<script>
	var curUrl ="";
	$(document).ready(function() 
    { 
        $("#prospResTab").tablesorter(); 
        $("#prospResTab").tablesorter({ headers: { 0: { sorter: false} } }); 
    	curUrl = $(location).attr('href');
    }); 
    
	function exportToXl() {
		var excelHtml = "<table><tr><th>E.I.N</th><th>Name</th><th>In care of name</th><th>Address</th><th>City</th>"
					+"<th>State</th><th>Zip Code</th><th>Asset Amount</th><th>Income Amount</th>"
				+"<th>Form 990 Rev. Amount</th><th>First Name</th><th>Last Name</th>"
				+"<th>Email</th><th>Title</th><th>Has Donation Button(true/false)</th><th>Website</th></tr>";
		
		$(".prosp-res-tab tr:has(input:checked)").each(function(){
			excelHtml = excelHtml + "<tr>";
			var count =1;
			$(this).find("td:not(#xlExcld)").each(function(){
				if(count==2 || count==3 || count==4 || count==5)
				{
					excelHtml = excelHtml + "<td>=PROPER(\"" + $(this).html() + "\")</td>";
				}
				else
				{
					excelHtml = excelHtml + "<td>" + $(this).html() + "</td>";
				}
				count=count+1;
			});			
			excelHtml = excelHtml + "<td></td><td></td><td></td><td></td><td></td><td></td></tr>";
			
		});			
		
		excelHtml = excelHtml + "</table>";
		
	    window.open('data:application/vnd.ms-excel,' + encodeURIComponent(excelHtml + "</table>"));
	}
	var isChecked = 0;
	function chkUnchkAll() {
		if ($(".mstrDelChkBox").is(":checked")) {
			$('.delChkBox').attr('checked', 'checked');
		} else {
			$('.delChkBox').removeAttr('checked');
		}
	}

	function delProspects() {
		var delProspectIds = "";
		var chkBoxes = $("input:checked");
		i = chkBoxes.length;
		if (i == 0) {
			alert("Please select a Prospect to delete");
		} 
		else
		{
			while (i--) {
				delProspectIds = delProspectIds + chkBoxes[i].id + "$";
			}
			var cnfrm = confirm("Are you sure you want to delete "+chkBoxes.length+" prospects?");
			if (cnfrm)
			{
				$.ajax({
					type : 'POST',
					beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')) },
					url : '/delProspects',
					data : {
						'delProspectIds' : delProspectIds,
					},
					success : function() {
						alert(chkBoxes.length + " Prospects deleted successfully!");
						window.location.href = curUrl;
					}
				});				
			}
		}
	}

</script>
<div align="center" style="padding:5px;height:520px; width:1200px;" >
	<%= form_tag search_path, :method => 'get' do %>
	<table class="prosp-master-tab" style="border:none;">
		<tr>
			<td style="padding:0px;">
			<table class="srch-fields-tab">
				<tr>
					<td><%= label :name, "Name: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchName, params[:srchName] %></td>
				</tr>
				<tr>
					<td><%= label :e_i_n, "E I N: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchEin, params[:srchEin] %></td>
				</tr>
				<tr>
					<td><%= label :in_care_of_name, "In care of name: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchInCareOfName, params[:srchInCareOfName] %></td>
				</tr>
				<tr>
					<td><%= label :address, "Address: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchAddr, params[:srchAddr] %></td>
				</tr>
				<tr>
					<td><%= label :city, "City: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchCity, params[:srchCity] %></td>
				</tr>
				<tr>
					<td><%= label :state, "State: " %></td>
				</tr>
				<tr>
					<td>
					<select id="srchState" name="srchState" >
						<option selected="selected" value=""></option>
						<option value="AL">AL</option>
						<option value="AK">AK</option>
						<option value="AZ">AZ</option>
						<option value="AR">AR</option>
						<option value="CA">CA</option>
						<option value="CO">CO</option>
						<option value="CT">CT</option>
						<option value="DE">DE</option>
						<option value="DC">DC</option>
						<option value="FL">FL</option>
						<option value="GA">GA</option>
						<option value="HI">HI</option>
						<option value="ID">ID</option>
						<option value="IL">IL</option>
						<option value="IN">IN</option>
						<option value="IA">IA</option>
						<option value="KS">KS</option>
						<option value="KY">KY</option>
						<option value="LA">LA</option>
						<option value="ME">ME</option>
						<option value="MD">MD</option>
						<option value="MA">MA</option>
						<option value="MI">MI</option>
						<option value="MN">MN</option>
						<option value="MS">MS</option>
						<option value="MO">MO</option>
						<option value="MT">MT</option>
						<option value="NE">NE</option>
						<option value="NV">NV</option>
						<option value="NH">NH</option>
						<option value="NJ">NJ</option>
						<option value="NM">NM</option>
						<option value="NY">NY</option>
						<option value="NC">NC</option>
						<option value="ND">ND</option>
						<option value="OH">OH</option>
						<option value="OK">OK</option>
						<option value="OR">OR</option>
						<option value="PA">PA</option>
						<option value="RI">RI</option>
						<option value="SC">SC</option>
						<option value="SD">SD</option>
						<option value="TN">TN</option>
						<option value="TX">TX</option>
						<option value="UT">UT</option>
						<option value="VT">VT</option>
						<option value="VA">VA</option>
						<option value="WA">WA</option>
						<option value="WV">WV</option>
						<option value="WI">WI</option>
						<option value="WY">WY</option>
					</select></td>
				</tr>
				<tr>
					<td><%= label :zip_code, "Zip Code: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchZipCode, params[:srchZipCode] %></td>
				</tr>
				<tr>
					<td><%= label :asset_amount, "Asset Amount: " %><i style="font-size: 10px;">(e.g., >100)</i></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchAstAmnt, params[:srchAstAmnt] %></td>
				</tr>
				<tr>
					<td><%= label :income_amount, "Income Amount: " %><i style="font-size: 10px;">(e.g., >100)</i></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchIncAmnt, params[:srchIncAmnt] %></td>
				</tr>
				<tr>
					<td><%= label :form_990_revenue_amount, "Form amount: " %><i style="font-size: 10px;">(e.g., >100)</i></td>
				</tr>
				<tr>
					<td><%= text_field_tag :srchFrm990RvnAmnt, params[:srchFrm990RvnAmnt] %></td>
				</tr>
				<tr>
					<td><%= label :limit_records, "Limit No. of Records to: " %></td>
				</tr>
				<tr>
					<td><%= text_field_tag :recLimit, params[:recLimit] %></td>
				</tr>
				<tr>
					<td>&nbsp;&nbsp;<%= submit_tag "Search", :name => nil %></td>
				</tr>
			</table></td>
			<td style="padding-top:0px;">
			<table style="border:none;">
				<tr>
					<td>
					<div class="scrollContent">
						<table id="prospResTab" class="prosp-res-tab">
							<thead>
							<tr class="prosp-res-hdr">
								<th id="xlExcld">
								<input class="mstrDelChkBox" type="checkbox" onclick="chkUnchkAll();" >
								</th>
								<th>E.I.N</th>
								<th>Name</th>
								<th>In care of name</th>
								<th>Address</th>
								<th>City</th>
								<th>State</th>
								<th>Zip code</th>
								<th>Asset amount</th>
								<th>Income amount</th>
								<th>Form 990 rev. amount</th>
								<th id="xlExcld">-</th>
								<th id="xlExcld">-</th>
							</tr>
							</thead>
							<tbody>
							<% if @wdi_prospects %>
							<% @wdi_prospects.each do |wdi_prospect| %>
							<tr>
								<td id="xlExcld">
								<input class="delChkBox" type="checkbox" id="<%= wdi_prospect.id %>" >
								</td>
								<td><%= wdi_prospect.e_i_n %></td>
								<td><%= wdi_prospect.name %></td>
								<td><%= wdi_prospect.in_care_of_name %></td>
								<td><%= wdi_prospect.address %></td>
								<td><%= wdi_prospect.city %></td>
								<td><%= wdi_prospect.state %></td>
								<td><%= wdi_prospect.zip_code %></td>
								<td>$<%= number_with_delimiter(wdi_prospect.asset_amount, :delimiter => ',') %></td>
								<td>$<%= number_with_delimiter(wdi_prospect.income_amount, :delimiter => ',') %></td>
								<td>$<%= number_with_delimiter(wdi_prospect.form_990_revenue_amount, :delimiter => ',') %></td>
								<!--td><%= link_to 'Show', wdi_prospect %></td-->
								<!--td><%= link_to 'Edit', edit_wdi_prospect_path(wdi_prospect) %></td-->
								<td id="xlExcld"><%= link_to 'Edit', edit_wdi_prospect_path(wdi_prospect) %></td>
								<td id="xlExcld"><%= link_to 'Destroy', wdi_prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							</tr>
							<% end %>
							<% end %>
							</tbody>
						</table>
					</div></td>
				</tr>
				<tr>
					<td style="border: 1px solid #7EBD64;border-left:none;">&nbsp;&nbsp;<%= button_to_function "Delete", 'delProspects();', :id => "delBtn" %>
						&nbsp;&nbsp;<input style="width:120px;" type="button" onclick="exportToXl();" value="Export to Excel">
					</td>
				</tr>

			</table></td>
		</tr>
	</table>
	<% end %>
</div>

WDI Prospects Browser/app/views/wdi_prospects/show.html.erb
<div class="center-div">
	<p id="notice"><%= notice %></p>
	
	<p>
	  <b>E i n:</b>
	  <%= @wdi_prospect.e_i_n %>
	</p>
	
	<p>
	  <b>Name:</b>
	  <%= @wdi_prospect.name %>
	</p>
	
	<p>
	  <b>In care of name:</b>
	  <%= @wdi_prospect.in_care_of_name %>
	</p>
	
	<p>
	  <b>Address:</b>
	  <%= @wdi_prospect.address %>
	</p>
	
	<p>
	  <b>City:</b>
	  <%= @wdi_prospect.city %>
	</p>
	
	<p>
	  <b>State:</b>
	  <%= @wdi_prospect.state %>
	</p>
	
	<p>
	  <b>Zip code:</b>
	  <%= @wdi_prospect.zip_code %>
	</p>
	
	<p>
	  <b>Asset amount:</b>
	  <%= @wdi_prospect.asset_amount %>
	</p>
	
	<p>
	  <b>Income amount:</b>
	  <%= @wdi_prospect.income_amount %>
	</p>
	
	<p>
	  <b>Form 990 revenue amount:</b>
	  <%= @wdi_prospect.form_990_revenue_amount %>
	</p>
<%= link_to 'Edit', edit_wdi_prospect_path(@wdi_prospect) %>

</div>

WDI Prospects Browser/app/views/wdi_prospects/uploadfile.html.erb
<div class="center-div">

	<h1>Upload CSV File</h1>

	<p id="notice">
		<b>Select CSV file containing prospects:</b>
	</p>
	<%=form_tag import_path, multipart: true do %>
	<%= file_field_tag :file %>
	<br />
	<br />
	<input style="width:120px;" type="submit" value="Import Records" name="commit" />
	<% end %>
	<br />
	<p id="notice">
		<i><b><u><%= notice %></u></b></i>
	</p>
	<br />
	<p id="notice">
		<b>Select CSV file containing refined prospects:</b>
	</p>
	<%=form_tag import_to_refined_path, multipart: true do %>
	<%= file_field_tag :file %>
	<br />
	<br />
	<input style="width:120px;" type="submit" value="Import Records" name="commit" />
	<% end %>
</div>